objects:
  - type: DatasetObject     
    name: erlenmeyer_flask_1
    category: erlenmeyer_flask
    model: bpwjxr
    position: [0.165, 1.4, 0.96]
    orientation: [0, 0, 0, 1]
    scale: [1.5, 1.5, 1]

  - type: DatasetObject     
    name: magnetic_stirrer_1
    category: magnetic_stirrer
    model: xtamki
    position: [0.18, 1.15, 1]
    orientation: [0, 0, 0, 1]
    scale: [1, 1, 1]

